name = "ratpack"
author = "navarchus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b5091bce195964dea36387de89318d57e09b3c1aa032060d5056b775d597bf0b"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
