name = "ratpack"
author = "navarchus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f53175057175df81148670f910be9be6a271829c56c215dfce5509fa9ba5abf"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
