name = "ratpack"
author = "navarchus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "daded884f54056b563a303d94545fc222d7ea64c95a7ae126088c672a62d158a"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
