name = "ratpack"
author = "navarchus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db6bd0af88a23780e786058133b093c26cfd336150abcc5c7aa0593d9a91bafe"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
