name = "ratpack"
author = "navarchus"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77ce6b1f9b9d6428de8d77764cc133290952aa848859c7b87b9008432e698403"

[versions]
fabric = "0.17.2"
minecraft = "1.20.1"
